"""
This is a short script useful the features maps generated by the model.
"""

import keras
import tensorflow as tf
import numpy as np

from keras.models import Model
from matplotlib import pyplot

# load the model
from Models.Model import dice_loss, dice_coeff

model = keras.models.load_model('Trained Models/mask_yellow.h5',
                                custom_objects={'dice_loss': dice_loss, 'dice_coeff': dice_coeff})

# redefine model to output right after the first hidden layer
ixs = [12, 19, 26, 33]
outputs = [model.layers[i].output for i in ixs]
model = Model(inputs=model.inputs, outputs=outputs)

# load image
img = tf.keras.utils.load_img('PDT detection\SolanumTuberosum\TrainImages\img_0187.png')
img = np.expand_dims(np.array(img), axis=0)

# get feature map for first hidden layer
feature_maps = model.predict(img)

# plot the output from each block
square = 4
for fmap in feature_maps:
    # plot all 64 maps in an 8x8 squares
    ix = 1
    for _ in range(square):
        for _ in range(square):
            # specify subplot and turn of axis
            ax = pyplot.subplot(square, square, ix)
            ax.set_xticks([])
            ax.set_yticks([])
            # plot filter channel in grayscale
            pyplot.imshow(fmap[0, :, :, ix - 1], cmap='gray')
            ix += 1
    # show the figure
    pyplot.show()